### ISSUE TITLE
Last frame of animation to remain on screen.

### ISSUE THREAD

**Issue by JovieBrett** [skyfe79/FAImageView#4]
Is there a way to make the last frame of the animation to remain on screen after the animation is done? 
Edit:
I duplicated the last frames to fix it.

**Comment by skyfe79** [comment]
Hello JovieBrett,
You can use setRestoreFirstFrameWhenFinishAnimation method like below.

```
faImageViewInstance.setRestoreFirstFrameWhenFinishAnimation(false)
```

I also update FAImageView to 0.0.4 version. It contains some callbacks for animation lifecycle and fixed some bugs.

I hope this helps you :)
