### ISSUE TITLE
can you add more ways on method addimageFrame();

### ISSUE THREAD

**Issue by caoyanglee** [skyfe79/FAImageView#7]

**Comment by skyfe79** [comment]
Hello chi5hao,

I added more method to add Image Frame like below:
- addImageFrame(Drawable drawable)
- addImageFrame(Bitmap bitmap)

I updated [SplashActivity](https://github.com/skyfe79/FAImageView/blob/master/app/src/main/java/kr/pe/burt/android/lib/faimageview/app/SplashActivity.java) to use above new methods for frame animation. 

I hope this helps you :)
